name: Convert-PEM
version: 0.07
abstract: Read/write encrypted ASN.1 PEM files
author: Benjamin Trott <ben+cpan@stupidfool.org>
license: perl
distribution_type: module
requires:
  Class::ErrorHandler: 0
  MIME::Base64: 0
  Convert::ASN1: 0.10
  Digest::MD5: 0
  Crypt::DES_EDE3: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.36
